name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4 
      with: 
        version: latest
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: pnpm

    - name: Install dependencies 
      run: pnpm install
      
    - name: Build site
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      run: pnpm run build
      
    - name: Deploy to server
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        source: "dist/*"
        target: ${{ secrets.DEPLOY_PATH }}
        strip_components: 1